[custom]
;不要随意改变关键字，否则会导致出错
;https://lwnlh.com/15_Clash_Custom_Triage_Rules.html

;去广告：支持
;自动测速：支持
;微软分流：支持
;苹果分流：支持
;增强中国IP段：支持
;增强国外GFW：支持

;设置规则标志位
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaIp.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/xlldll/sing-box-subscribe/refs/heads/main/Custom.list
ruleset=🐟 漏网之鱼,[]FINAL
;设置规则标志位

;设置分组标志位
custom_proxy_group=🚀 节点选择`select`[]📺 Emby节点`[]🚀 手动切换`[]DIRECT
custom_proxy_group=📺 Emby节点`url-test`(香港|澳门|越南|韩国|泰国|菲律宾|新加坡|马来西亚|印度尼西亚|移动)`http://www.gstatic.com/generate_204`30,,50
custom_proxy_group=🚀 手动切换`select`.*
custom_proxy_group=🎯 全球直连`select`[]DIRECT
custom_proxy_group=🐟 漏网之鱼`select`[]🚀 节点选择`[]DIRECT`[]📺 Emby节点`[]🚀 手动切换
custom_proxy_group=🙅 故障转移`fallback`[]DIRECT`[]🚀 手动切换

;设置分组标志位

enable_rule_generator=true
overwrite_original_rules=true
